remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: Computational intelligence Lab
description: On the one hand, new algorithms and methods (theory) are developed and, on the other hand, computational intelligence techniques are applied to image processing, biomedical signal processing, time series processing in astronomy, optimal battery packaging design and data mining.
